### ISSUE TITLE
I have some questions, can you help me！！！

### ISSUE THREAD

**Issue by huangwanhua99** [hkmztrk/DeepDTA#36]
When I run deepdta-toy/run_experiments.py, I always have Traceback (most recent call last):
   File "run_experiments.py", line 551, in <module>
     prepare_new_data(FLAGS. test_path, test=True)
   File "C:\Users\75172\Desktop\School of Life Sciences\code\DeepDTA-master\deepdta-toy\testdatahelper.py", line 14, in prepare_new_data
     prots = read_proteins(fpath)
   File "C:\Users\75172\Desktop\School of Life Sciences\code\DeepDTA-master\deepdta-toy\testdatahelper.py", line 60, in read_proteins
     with open(filename) as f:
FileNotFoundError: [Errno 2] No such file or directory: '/data/mytest/proteins.fasta'
this mistake

**Comment by hkmztrk** [comment]
Hi @huangwanhua99 

in case you haven't solve this, the error message indicates that it can't find the files that are needed to run the toy experiment. Please either download the example files from here https://github.com/hkmztrk/DeepDTA/tree/master/deepdta-toy/data or provide your own set of inputs.
