### ISSUE TITLE
Install tensorflow=1.x needs python>=3.5

### ISSUE THREAD

**Issue by rex-29** [hkmztrk/DeepDTA#45]
Hi, i just meet the problem that install tensorflow in 1.X version, it said need python 3.5 or above, but your requirement is python <= 3.4, so I want to know how to fix the problem.

(drug) root@63bbu73rbh5p3-0:/dengby# pip install tensorflow -i https://pypi.tuna.tsinghua.edu.cn/simple
Traceback (most recent call last):
  File "/opt/conda/envs/drug/bin/pip", line 6, in <module>
    from pip._internal.cli.main import main
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_internal/cli/main.py", line 10, in <module>
    from pip._internal.cli.autocompletion import autocomplete
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_internal/cli/autocompletion.py", line 9, in <module>
    from pip._internal.cli.main_parser import create_main_parser
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_internal/cli/main_parser.py", line 7, in <module>
    from pip._internal.cli import cmdoptions
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_internal/cli/cmdoptions.py", line 25, in <module>
    from pip._internal.cli.progress_bars import BAR_TYPES
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_internal/cli/progress_bars.py", line 12, in <module>
    from pip._internal.utils.logging import get_indentation
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_internal/utils/logging.py", line 18, in <module>
    from pip._internal.utils.misc import ensure_dir
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_internal/utils/misc.py", line 21, in <module>
    from pip._vendor import pkg_resources
  File "/opt/conda/envs/drug/lib/python3.4/site-packages/pip/_vendor/pkg_resources/__init__.py", line 92, in <module>
    raise RuntimeError("Python 3.5 or later is required")
RuntimeError: Python 3.5 or later is required

Thanks!!!

**Comment by hkmztrk** [comment]
Hi @Rex-Tang, please see  issue #37  for updated package versions
